### ISSUE TITLE
Add information to the Wiki about bounce messages in the support inbox (not on requests)

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1197]
We've received a bounce message in the inbox, so I looked up the email, found the user, noticed no bounce had been recorded there, noted that on the thread, and looked on the Wiki for what to do next, but didn't find anything, so just left the thread in the inbox.

**Todo:**

- [x] Establish what actually should be done in such circumstances
- [x] Add it to the Wiki (probably on the [Support mailbox](https://wdtkwiki.mysociety.org/wiki/Support_mailbox) page)
- [ ] Update the wiki page when mysociety/alaveteli/issues#6297 has been implemented.

**Comment by garethrees** [comment]
Send to `dev@` for manual recording. See also https://github.com/mysociety/alaveteli/issues/6297.

**Comment by sallytay** [comment]
That looks good to me, thank you

**Comment by HelenWDTK** [comment]
Closing as stale, and stalled on https://github.com/mysociety/alaveteli/issues/6297
