### ISSUE TITLE
Improve GDPR request metadata [TODO]

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#701]
When handling support requests in regard to GDPR / DPA rights, we generate metadata which can be used to improve and refine our processes.

It is important that we capture this data in a way that lets us quickly analyse it and get a sense of "what is working" and "what can we do better".

We already have a basic tracking system for requests - this TODO aims to build on that to improve the accuracy of the metadata and refine the system to make it easier to use.

**Comment by mdeuk** [comment]
An initial update was made at the end of May which:

- Added logic to automatically generate case reference numbers (GDPR/right/date-sequence)
- Standardised the entry of scope, compliance, erasure, and rights fields.
- Added colour coding to allow active requests to be easily distinguished by status (e.g. Pending, Comply, and so on)

**Comment by mdeuk** [comment]
Some further updates were made in June:

- Add and improve pivot table tracking request types and compliance
- Standardisation of old metadata to retrospectively track those requests by a standard *right*
- Addition of additional *status* options to reflect case handling practices
- Added BR and PE as *rights* to allow tracking of compliance measures.

An additional update was made in early July:

- Improved logic used for generating case *deadlines* in order to better account for cases with different handling requirements.

**Comment by mdeuk** [comment]
### Work to follow

- Improve documentation held on the WDTKWiki knowledge base
- Consider improvements to data entry (forms?) and display
- Consider improvements to how we track status changes

**Comment by RichardTaylor** [comment]
Perhaps this is a good place to record some suggestions for the tracking spreadsheet, from the perspective of using it to carry out a review of the current position:

* Order by due date, with the most recent due date at the top. 
* Bold / red or otherwise mark rows where the due date has passed (and maybe orange if they are within say 3 days)
* Change the name of the "pending" classification to "clarification awaited" and make rows marked as such greyed out.  as we don't need to act further on them if no clarification is forthcoming.    (Recently "pending" was used for both cases under discussion and where clarification was awaited). 

In relation to data breach cases:
* Consider cases where we're tracking two deadlines, one for an initial report and one for our internal deadline to review and consider deleting material. 
* Note we don't have any formal legal deadline for reporting data breaches by others to the ICO. 

Can one have scripts which can be set to run daily from a Google sheets spreadsheet to send an email. An email alert to the volunteers list or support mailbox if a deadline was approaching is perhaps technically possible:

https://www.quora.com/How-can-I-periodically-run-a-Google-Script-on-a-Spreadsheet

**Comment by mdeuk** [comment]
Bug: When a case where we've served a §52(4)(b) notice has its 'received' date changed, in order to accurately reflect the revised deadline, the sheet automatically renumbers the case along with any others that fall below it (as it works on a sequential basis).

We should devise a solution that allows for re-factoring of deadlines without changing the case identifier.

**Comment by mdeuk** [comment]
> * Order by due date, with the most recent due date at the top.

Currently it's not possible to do this - it breaks the sequencing. It may, however, be possible to implement a "view" (pivot table or otherwise) which captures this data. #704 

> * Bold / red or otherwise mark rows where the due date has passed (and maybe orange if they are within say 3 days)

This should be possible, however, it will likely need some scripting. #704 

> * Change the name of the "pending" classification to "clarification awaited" and make rows marked as such greyed out as we don't need to act further on them if no clarification is forthcoming.    (Recently "pending" was used for both cases under discussion and where clarification was awaited).

As an interim solution, there is now a dropdown for "On hold (awaiting user)" and a corresponding conditional formatting rule, which evaluates column H for this status and greys out the contents of the row. I think there is possibly a better way of doing this than using conditional formatting, but this is an interim and it copies what was already in place for the "Done?" column (A).

> Can one have scripts which can be set to run daily from a Google sheets spreadsheet to send an email? An email alert to the volunteers list or support mailbox if a deadline was approaching is perhaps technically possible:
> 
> https://www.quora.com/How-can-I-periodically-run-a-Google-Script-on-a-Spreadsheet

Yes - however, it does require writing some code to evaluate the sheet for content. I'm working on a prototype which does this and handles sending of some of the transactional content (e.g. acknowledgements, internal notes of tracking numbers). #704 

There are some limitations that we'll encounter using GS for this purpose, but it does seem reasonable for now - it is readily available and has some useful functionality under the hood.

**Comment by garethrees** [comment]
> We should devise a solution that allows for re-factoring of deadlines without changing the case identifier.
> …
> Currently it's not possible to do this - it breaks the sequencing.

I think it's important that the ID gets fixed once it's been set. My preference would be to go back to manual ID assignment over IDs that are mutable.

Wonder if we could use the script editor to add a "New ID Generator" command?

**Comment by mdeuk** [comment]
> > We should devise a solution that allows for re-factoring of deadlines without changing the case identifier.
> > …
> > Currently it's not possible to do this - it breaks the sequencing.
> 
> I think it's important that the ID gets fixed once it's been set. My preference would be to go back to manual ID assignment over IDs that are mutable.
> 
> Wonder if we could use the script editor to add a "New ID Generator" command?

Agreed - what we've got now is very much the minimum viable product, it works, but it isn't necessarily the best way of doing things.

The formula method works correctly in all but a few of the cases we have just now, so I think we should keep it _for now_, however, once case entry is refactored (likely via an appscript) we should move to something a little more robust.

**Comment by MattK1234** [comment]
Just to note it might be a good quality assurance enhancement to technically enforce the 'Decision' column being in a completed state before the Done tickbox can be ticked.

For example when looking through the spreadsheet I noticed a case that was ticked as Done with the decision still listed as pending.

I don't think this is important, but more of a nice-to-have.

**Comment by mdeuk** [comment]
For RoAR / SARs, the tracker should:
- [ ] Create a folder structure when a new case is added
- [ ] produce the Process Doc and the initial response letter automatically
- [ ] Allow cases to be flagged  as 'ready for review' so that the reviewer is able to interact
- [ ] Allow cases to be flagged as complete, allowing the audit log to be finalised https://github.com/mysociety/whatdotheyknow-theme/issues/701#issuecomment-679357062
- [ ] Record outcome when marked as complete, to assist with metadata collection https://github.com/mysociety/whatdotheyknow-theme/issues/923#issue-1048547820
